language: csharp
solution: Overflow.net.sln
install:
  - nuget restore Overflow.net.sln
  - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release Overflow.net.sln
  - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./test/Overflow.Test/bin/Release/Overflow.Test.dll
