language: csharp
mono: none
dotnet: 1.0.0
solution: Overflow.net.sln
install:
- nuget restore Overflow.net.sln
- nuget install xunit.runner.console -ExcludeVersion -OutputDirectory testrunner
script:
- xbuild /p:Configuration=Release Overflow.net.sln
#- mono ./testrunner/xunit.runner.console/tools/xunit.console.exe ./test/Overflow.Test/bin/Release/Overflow.Test.dll
notifications:
  slack:
    secure: RwlN5jiS9z6oJAQRl10mIjcEP4KU+jaHdlQK7VV7zTG/O1SKVwwmW7OlZmUojIRKV5GQ0KE7z4NyPL+qsiudbsQfeZ4ZqKD9c2eUTgMbVZp9A7MPy3eYsmpbeuTaB7mX+8pAysp+IJGH/5U3rj0ez1pCd4HwK+Leoddmn+xHsmo=
  email: false
dist: trusty
sudo: required