language: csharp
mono: none
dotnet: 1.0.0
solution: Overflow.net.sln
install:
- dotnet restore
- dotnet build /src/Overflow/project.json
- dotnet build /test/Overflow.Test/project.json
script:
- dotnet test /test/Overflow.Test/project.json
notifications:
  slack:
    secure: RwlN5jiS9z6oJAQRl10mIjcEP4KU+jaHdlQK7VV7zTG/O1SKVwwmW7OlZmUojIRKV5GQ0KE7z4NyPL+qsiudbsQfeZ4ZqKD9c2eUTgMbVZp9A7MPy3eYsmpbeuTaB7mX+8pAysp+IJGH/5U3rj0ez1pCd4HwK+Leoddmn+xHsmo=
  email: false
dist: trusty
sudo: required